
services:
  puppeteer-crawler:
    build:
      context: .
    image: ivannglivelyimpact/puppeteer-crawler
    container_name: puppeteer-crawler
    ports:
      - 3000:3000
      - 5900:5900
    volumes:
      - ./log:/app/log
      - ./output:/app/output
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PROXY_URL: ${PROXY_URL}
      LOG_LEVEL: debug
